### ISSUE TITLE
show hotel picture, reviews, description and possible other details from google places 

### ISSUE THREAD

**Issue by joachimprinzbach** [joachimprinzbach/ng2-camp#21]

**Comment by marcosteybe** [comment]
Sample Request:
https://maps.googleapis.com/maps/api/place/details/json?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4&key=%20AIzaSyBviGjjZKy0op-C6YncrFJsIRBOZwtL-WQ

**Comment by joachimprinzbach** [comment]
This issue was moved to joachimprinzbach/ng2-camp2#9
