### ISSUE TITLE
Replace existing datepickers with material2 datepicker

### ISSUE THREAD

**Issue by marcosteybe** [joachimprinzbach/ng2-camp#34]
Currently there are at least 2 different styles of date pickers integrated into the app. See for example date picker for offer creation vs date picker for camp creation (in camp workflow)!

**Comment by ailedt** [comment]
- use material2 datepicker once ready and replace existing datepickers in app. make sure dates are prefilled when editing offerRequests or offers in application..
https://github.com/angular/material2

**Comment by joachimprinzbach** [comment]
This issue was moved to joachimprinzbach/ng2-camp2#2
